import PokemonContextProvider from "@/context/pokemonContextProvider";
import Main from "../components/main/Main";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PokemonContextProvider>
         <Main/>
      </PokemonContextProvider>
    </>
  );
}
